//----------------------
// <auto-generated>
//	Generated by T4StateMachine.
// </auto-generated>
//----------------------
// ReSharper disable All
using System;
using System.Collections.Generic;
using Stateless;

namespace T4Stateless.Tests
{
    using Models;

    public enum SmartphoneEvent
    {
        Boot,
        Call,
        TurnOff,
        Cancel,
        Connect,
        HungUp,
        PlaceOnHold,
        Resume,
    }

    public abstract class SmartphoneFireBaseEvent
    {
        protected SmartphoneFireBaseEvent(Smartphone item, SmartphoneEvent evt, bool isReentry)
        {
            Smartphone = item;
            Event = evt;
            IsReentry = isReentry;
        }

        public Smartphone Smartphone { get; }

        public SmartphoneEvent Event { get; }

        public bool IsReentry { get; }
    }
    public class SmartphoneFireBootReentryEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFireBootReentryEvent(SmartphoneState state, Smartphone item) : base(item, SmartphoneEvent.Boot, true)
        {
            State = state;
        }
        
        public SmartphoneState State { get; }
    }

    public class SmartphoneFireBootEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFireBootEvent(SmartphoneState oldState, SmartphoneState newState, Smartphone item) : base(item, SmartphoneEvent.Boot, false)
        {
            OldState = oldState;
            NewState = newState;
        }
        
        public SmartphoneState OldState { get; }

        public SmartphoneState NewState { get; }
    }

    public class SmartphoneFireCallEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFireCallEvent(SmartphoneState oldState, SmartphoneState newState, Smartphone item, string parameter) : base(item, SmartphoneEvent.Call, false)
        {
            OldState = oldState;
            NewState = newState;
            Parameter = parameter;
        }
        
        public SmartphoneState OldState { get; }

        public SmartphoneState NewState { get; }

        public string Parameter { get; }
    }

    public class SmartphoneFireTurnOffEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFireTurnOffEvent(SmartphoneState oldState, SmartphoneState newState, Smartphone item) : base(item, SmartphoneEvent.TurnOff, false)
        {
            OldState = oldState;
            NewState = newState;
        }
        
        public SmartphoneState OldState { get; }

        public SmartphoneState NewState { get; }
    }

    public class SmartphoneFireCancelEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFireCancelEvent(SmartphoneState oldState, SmartphoneState newState, Smartphone item) : base(item, SmartphoneEvent.Cancel, false)
        {
            OldState = oldState;
            NewState = newState;
        }
        
        public SmartphoneState OldState { get; }

        public SmartphoneState NewState { get; }
    }

    public class SmartphoneFireConnectEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFireConnectEvent(SmartphoneState oldState, SmartphoneState newState, Smartphone item) : base(item, SmartphoneEvent.Connect, false)
        {
            OldState = oldState;
            NewState = newState;
        }
        
        public SmartphoneState OldState { get; }

        public SmartphoneState NewState { get; }
    }

    public class SmartphoneFireHungUpEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFireHungUpEvent(SmartphoneState oldState, SmartphoneState newState, Smartphone item) : base(item, SmartphoneEvent.HungUp, false)
        {
            OldState = oldState;
            NewState = newState;
        }
        
        public SmartphoneState OldState { get; }

        public SmartphoneState NewState { get; }
    }

    public class SmartphoneFirePlaceOnHoldEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFirePlaceOnHoldEvent(SmartphoneState oldState, SmartphoneState newState, Smartphone item) : base(item, SmartphoneEvent.PlaceOnHold, false)
        {
            OldState = oldState;
            NewState = newState;
        }
        
        public SmartphoneState OldState { get; }

        public SmartphoneState NewState { get; }
    }

    public class SmartphoneFireResumeEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFireResumeEvent(SmartphoneState oldState, SmartphoneState newState, Smartphone item) : base(item, SmartphoneEvent.Resume, false)
        {
            OldState = oldState;
            NewState = newState;
        }
        
        public SmartphoneState OldState { get; }

        public SmartphoneState NewState { get; }
    }

    public class SmartphoneFireResumeReentryEvent : SmartphoneFireBaseEvent
    {
        public SmartphoneFireResumeReentryEvent(SmartphoneState state, Smartphone item) : base(item, SmartphoneEvent.Resume, true)
        {
            State = state;
        }
        
        public SmartphoneState State { get; }
    }


    public interface ISmartphoneStateMachineProvider
    {
        SmartphoneStateMachine Create(Smartphone item);
    }

    public partial class SmartphoneStateMachine
    {
        private readonly StateMachine<SmartphoneState, SmartphoneEvent> _sm;
        private readonly Smartphone _item;
        private readonly Action<SmartphoneFireBaseEvent> _handleEventAction;
        private Dictionary<SmartphoneEvent, Dictionary<Type, StateMachine<SmartphoneState, SmartphoneEvent>.TriggerWithParameters>> _parameters =
            new Dictionary<SmartphoneEvent, Dictionary<Type, StateMachine<SmartphoneState, SmartphoneEvent>.TriggerWithParameters>>();

        public SmartphoneStateMachine(Smartphone item, Func<Smartphone, SmartphoneState> stateAccessor, Action<Smartphone, SmartphoneState> stateMutator, Action<SmartphoneFireBaseEvent> handleEventAction)
        {
            if (item == null)
            {
                throw new ArgumentNullException(nameof(item));
            }
            if (stateAccessor == null)
            {
                throw new ArgumentNullException(nameof(stateAccessor));
            }
            if (stateMutator == null)
            {
                throw new ArgumentNullException(nameof(stateMutator));
            }
            if (handleEventAction == null)
            {
                throw new ArgumentNullException(nameof(handleEventAction));
            }
            _item = item;
            _handleEventAction = handleEventAction;
            _sm = new StateMachine<SmartphoneState, SmartphoneEvent>(() => stateAccessor(_item), (val) => stateMutator(_item, val));
            _sm.OnUnhandledTrigger(OnTransitionDeclined);
            _sm.OnTransitioned(OnTransitioned);
            AddParameter(SmartphoneEvent.Call, typeof(string), _sm.SetTriggerParameters<string>(SmartphoneEvent.Call));

            Func<bool> predicateOffBoot1 = () => _item.BatteryLevel < 5;
            _sm.Configure(SmartphoneState.Off)
                .PermitReentryIf(SmartphoneEvent.Boot, predicateOffBoot1, "BatteryLevel < 5")
                .PermitIf(SmartphoneEvent.Boot, SmartphoneState.Idle, () => !predicateOffBoot1(), "Otherwise")
                .OnEntryFrom(SmartphoneEvent.Boot, t => HandleEvent(t))
                .OnEntryFrom(GetParameter<string>(SmartphoneEvent.Call), (p, t) => HandleEvent(t, p))
                .OnEntryFrom(SmartphoneEvent.TurnOff, t => HandleEvent(t))
                .OnEntryFrom(SmartphoneEvent.Resume, t => HandleEvent(t))
            ;

            Func<bool> predicateIdleCall1 = () => _item.SimInserted;
            Func<bool> predicateIdleCall2 = () => _item.BatteryLevel < 5;
            _sm.Configure(SmartphoneState.Idle)
                .PermitIf(SmartphoneEvent.Call, SmartphoneState.Calling, predicateIdleCall1, "SimInserted")
                .PermitIf(SmartphoneEvent.Call, SmartphoneState.Off, predicateIdleCall2, "BatteryLevel < 5")
                .PermitReentryIf(SmartphoneEvent.Call, () => !predicateIdleCall1() && !predicateIdleCall2(), "Otherwise")
                .Permit(SmartphoneEvent.TurnOff, SmartphoneState.Off)
                .OnEntryFrom(SmartphoneEvent.Boot, t => HandleEvent(t))
                .OnEntryFrom(GetParameter<string>(SmartphoneEvent.Call), (p, t) => HandleEvent(t, p))
                .OnEntryFrom(SmartphoneEvent.Cancel, t => HandleEvent(t))
                .OnEntryFrom(SmartphoneEvent.HungUp, t => HandleEvent(t))
            ;

            _sm.Configure(SmartphoneState.Calling)
                .Permit(SmartphoneEvent.Cancel, SmartphoneState.Idle)
                .Permit(SmartphoneEvent.Connect, SmartphoneState.CallConnected)
                .OnEntryFrom(GetParameter<string>(SmartphoneEvent.Call), (p, t) => HandleEvent(t, p))
            ;

            _sm.Configure(SmartphoneState.CallConnected)
                .Permit(SmartphoneEvent.HungUp, SmartphoneState.Idle)
                .Permit(SmartphoneEvent.PlaceOnHold, SmartphoneState.CallOnHold)
                .OnEntryFrom(SmartphoneEvent.Connect, t => HandleEvent(t))
                .OnEntryFrom(SmartphoneEvent.Resume, t => HandleEvent(t))
            ;

            Func<bool> predicateCallOnHoldResume1 = () => _item.BatteryLevel < 5;
            Func<bool> predicateCallOnHoldResume2 = () => _item.Locked;
            _sm.Configure(SmartphoneState.CallOnHold)
                .PermitIf(SmartphoneEvent.Resume, SmartphoneState.Off, predicateCallOnHoldResume1, "BatteryLevel < 5")
                .PermitReentryIf(SmartphoneEvent.Resume, predicateCallOnHoldResume2, "Locked")
                .PermitIf(SmartphoneEvent.Resume, SmartphoneState.CallConnected, () => !predicateCallOnHoldResume1() && !predicateCallOnHoldResume2(), "Otherwise")
                .OnEntryFrom(SmartphoneEvent.PlaceOnHold, t => HandleEvent(t))
                .OnEntryFrom(SmartphoneEvent.Resume, t => HandleEvent(t))
            ;

        }

        private void HandleEvent(StateMachine<SmartphoneState, SmartphoneEvent>.Transition transition)
        {
            if (transition.IsReentry)
            {
                switch (transition.Trigger)
                {
                    case SmartphoneEvent.Boot:
                        _handleEventAction(new SmartphoneFireBootReentryEvent(transition.Source, _item));
                        break;
                    case SmartphoneEvent.Resume:
                        _handleEventAction(new SmartphoneFireResumeReentryEvent(transition.Source, _item));
                        break;
                }
            }
            else
            {
                switch (transition.Trigger)
                {
                    case SmartphoneEvent.Boot:
                        _handleEventAction(new SmartphoneFireBootEvent(transition.Source, transition.Destination, _item));
                        break;
                    case SmartphoneEvent.TurnOff:
                        _handleEventAction(new SmartphoneFireTurnOffEvent(transition.Source, transition.Destination, _item));
                        break;
                    case SmartphoneEvent.Cancel:
                        _handleEventAction(new SmartphoneFireCancelEvent(transition.Source, transition.Destination, _item));
                        break;
                    case SmartphoneEvent.Connect:
                        _handleEventAction(new SmartphoneFireConnectEvent(transition.Source, transition.Destination, _item));
                        break;
                    case SmartphoneEvent.HungUp:
                        _handleEventAction(new SmartphoneFireHungUpEvent(transition.Source, transition.Destination, _item));
                        break;
                    case SmartphoneEvent.PlaceOnHold:
                        _handleEventAction(new SmartphoneFirePlaceOnHoldEvent(transition.Source, transition.Destination, _item));
                        break;
                    case SmartphoneEvent.Resume:
                        _handleEventAction(new SmartphoneFireResumeEvent(transition.Source, transition.Destination, _item));
                        break;
                }
            }
        }

        private void HandleEvent(StateMachine<SmartphoneState, SmartphoneEvent>.Transition transition, string param)
        {
            if (transition.IsReentry)
            {
                switch (transition.Trigger)
                {
                }
            }
            else
            {
                switch (transition.Trigger)
                {
                    case SmartphoneEvent.Call:
                        _handleEventAction(new SmartphoneFireCallEvent(transition.Source, transition.Destination, _item, param));
                        break;
                }
            }
        }

        public void FireBoot()
        {
            Fire(SmartphoneEvent.Boot);
        }

        public void FireCall(string parameter)
        {
            Fire(SmartphoneEvent.Call, parameter);
        }

        public void FireTurnOff()
        {
            Fire(SmartphoneEvent.TurnOff);
        }

        public void FireCancel()
        {
            Fire(SmartphoneEvent.Cancel);
        }

        public void FireConnect()
        {
            Fire(SmartphoneEvent.Connect);
        }

        public void FireHungUp()
        {
            Fire(SmartphoneEvent.HungUp);
        }

        public void FirePlaceOnHold()
        {
            Fire(SmartphoneEvent.PlaceOnHold);
        }

        public void FireResume()
        {
            Fire(SmartphoneEvent.Resume);
        }

        public bool CanFire(SmartphoneEvent evt)
        {
            return _sm.CanFire(evt);
        }

        public void Fire<T>(SmartphoneEvent evt, T parameter)
        {
            if (!CanFire(evt))
            {
                throw new ApplicationException($"Cannot fire event {evt} in the current state {_sm.State}");
            }
            var param = GetParameter<T>(evt);
            _sm.Fire(param, parameter);
        }

        public void Fire(SmartphoneEvent evt)
        {
            if (!CanFire(evt))
            {
                throw new ApplicationException($"Cannot fire event {evt} in the current state {_sm.State}");
            }
            _sm.Fire(evt);
        }

        private void AddParameter(SmartphoneEvent evt, Type paramType, StateMachine<SmartphoneState, SmartphoneEvent>.TriggerWithParameters trigger)
        {
            Dictionary<Type, StateMachine<SmartphoneState, SmartphoneEvent>.TriggerWithParameters> dict;
            if (!_parameters.TryGetValue(evt, out dict))
            {
                dict = new Dictionary<Type, StateMachine<SmartphoneState, SmartphoneEvent>.TriggerWithParameters>();
                _parameters.Add(evt, dict);
            }
            dict[paramType] = trigger;
        }

        private StateMachine<SmartphoneState, SmartphoneEvent>.TriggerWithParameters<T> GetParameter<T>(SmartphoneEvent evt)
        {
            Dictionary<Type, StateMachine<SmartphoneState, SmartphoneEvent>.TriggerWithParameters> dict;
            if (!_parameters.TryGetValue(evt, out dict))
            {
                throw new KeyNotFoundException($"Key {evt} was not found in trigger parameters dictionary");
            }
            return (StateMachine<SmartphoneState, SmartphoneEvent>.TriggerWithParameters<T>)dict[typeof(T)];
        }

        #region Transition events

        private void OnTransitioned(StateMachine<SmartphoneState, SmartphoneEvent>.Transition t)
        {
            // TODO: EVENT - $"Transitioned from state '{t.Source}' to state '{t.Destination}' with event {t.Trigger}"
        }

        private void OnTransitionDeclined(SmartphoneState state, SmartphoneEvent e)
        {
            // TODO: EVENT - $"Transitioned from state '{t.Source}' to state '{t.Destination}' with event {t.Trigger}"
            throw new ApplicationException($"Event '{e}' is not valid for state '{state}'");
        }

        #endregion


    }
}
